### ISSUE TITLE
Bootstrap with docker-compose

### ISSUE THREAD

**Issue by vitormattos** [LyseonTech/dashboard#5]
Project bootstrap creation using Docker containing the following services from official images:
- [x] nginx
- [x] PHP 7.3 fpm
- [x] MySQL

### Requirements
 - [x] Volume to DB data folder
 - [x] DB dumps folder volume
 - [x] Database access data defined in .env file
 - [x] If need `Dockerfile` or other files for a service, put it in the `.docker` folder on root of project, for example: `.docker/php7/Dockerfifle`, `.docker/mysql/Dockerfile`
 - [x] `docker-compose.yml` file should be at project root

**Comment by kathedrall** [comment]
I made changes to the project infrastructure, temporarily removed the environment variables from docker-compose and installed via phl the data structure module of php. I also noticed that the ngnix container did not talk to the php container, linked both containers and created a www directory to point the application, separating infrastructure from the rest of the project. I updated the composer version because it is not compatible with the php version installed in the project (dockerfile)
